create table Bakery_Menu (
	id SERIAL PRIMARY KEY,
	item_name VARCHAR(50),
	price DECIMAL(5,2)
);
insert into Bakery_Menu (item_name, price) values ('Flower - Commercial Bronze', 84.56);
insert into Bakery_Menu (item_name, price) values ('Cookie - Dough Variety', 74.08);
insert into Bakery_Menu (item_name, price) values ('Cheese - Marble', 2.73);
insert into Bakery_Menu (item_name, price) values ('Cookie Dough - Peanut Butter', 35.19);
insert into Bakery_Menu (item_name, price) values ('The Pop Shoppe - Black Cherry', 28.62);
insert into Bakery_Menu (item_name, price) values ('Nut - Hazelnut, Ground, Natural', 98.85);
insert into Bakery_Menu (item_name, price) values ('Mini - Vol Au Vents', 92.15);
insert into Bakery_Menu (item_name, price) values ('Liners - Baking Cups', 91.68);
insert into Bakery_Menu (item_name, price) values ('Pineapple - Canned, Rings', 24.67);
insert into Bakery_Menu (item_name, price) values ('Lettuce Romaine Chopped', 33.05);
insert into Bakery_Menu (item_name, price) values ('Beets', 42.06);
insert into Bakery_Menu (item_name, price) values ('Sword Pick Asst', 38.58);
insert into Bakery_Menu (item_name, price) values ('Wine - Alicanca Vinho Verde', 46.7);
insert into Bakery_Menu (item_name, price) values ('Pork - Loin, Bone - In', 45.2);
insert into Bakery_Menu (item_name, price) values ('French Kiss Vanilla', 37.12);
insert into Bakery_Menu (item_name, price) values ('Cookies - Oreo, 4 Pack', 89.49);
insert into Bakery_Menu (item_name, price) values ('Pepper - Red Chili', 29.54);
insert into Bakery_Menu (item_name, price) values ('Cheese - La Sauvagine', 27.1);
insert into Bakery_Menu (item_name, price) values ('Steel Wool S.o.s', 35.75);
insert into Bakery_Menu (item_name, price) values ('Chip - Potato Dill Pickle', 8.8);
insert into Bakery_Menu (item_name, price) values ('Beans - Black Bean, Dry', 68.23);
insert into Bakery_Menu (item_name, price) values ('Calaloo', 21.42);
insert into Bakery_Menu (item_name, price) values ('Wine - Ej Gallo Sierra Valley', 9.1);
insert into Bakery_Menu (item_name, price) values ('Wine - Pinot Noir Mondavi Coastal', 66.97);
insert into Bakery_Menu (item_name, price) values ('Wine - Red, Metus Rose', 13.1);
insert into Bakery_Menu (item_name, price) values ('Garbage Bags - Clear', 72.48);
insert into Bakery_Menu (item_name, price) values ('Wine - Two Oceans Cabernet', 40.32);
insert into Bakery_Menu (item_name, price) values ('Cup - 6oz, Foam', 43.37);
insert into Bakery_Menu (item_name, price) values ('Bay Leaf Fresh', 41.69);
insert into Bakery_Menu (item_name, price) values ('Beef - Rib Roast, Cap On', 50.38);
insert into Bakery_Menu (item_name, price) values ('Energy Drink - Franks Pineapple', 67.72);
insert into Bakery_Menu (item_name, price) values ('Skirt - 29 Foot', 76.65);
insert into Bakery_Menu (item_name, price) values ('Mountain Dew', 46.32);
insert into Bakery_Menu (item_name, price) values ('Pork - Bacon, Double Smoked', 96.78);
insert into Bakery_Menu (item_name, price) values ('Venison - Denver Leg Boneless', 49.15);
insert into Bakery_Menu (item_name, price) values ('Bacardi Breezer - Strawberry', 93.91);
insert into Bakery_Menu (item_name, price) values ('Soup - Boston Clam Chowder', 82.31);
insert into Bakery_Menu (item_name, price) values ('Browning Caramel Glace', 28.57);
insert into Bakery_Menu (item_name, price) values ('Peach - Fresh', 37.98);
insert into Bakery_Menu (item_name, price) values ('Black Currants', 83.43);
insert into Bakery_Menu (item_name, price) values ('Wine - Barossa Valley Estate', 34.46);
insert into Bakery_Menu (item_name, price) values ('Salt - Celery', 31.71);
insert into Bakery_Menu (item_name, price) values ('Garlic Powder', 39.82);
insert into Bakery_Menu (item_name, price) values ('Veal - Round, Eye Of', 24.51);
insert into Bakery_Menu (item_name, price) values ('Wine - Jaboulet Cotes Du Rhone', 94.91);
insert into Bakery_Menu (item_name, price) values ('Pasta - Fettuccine, Dry', 97.57);
insert into Bakery_Menu (item_name, price) values ('Wine - Red, Marechal Foch', 72.15);
insert into Bakery_Menu (item_name, price) values ('Molasses - Fancy', 32.71);
insert into Bakery_Menu (item_name, price) values ('Kaffir Lime Leaves', 56.83);
insert into Bakery_Menu (item_name, price) values ('Instant Coffee', 65.71);
insert into Bakery_Menu (item_name, price) values ('Cucumber - English', 68.3);
insert into Bakery_Menu (item_name, price) values ('Silicone Parch. 16.3x24.3', 75.97);
insert into Bakery_Menu (item_name, price) values ('Chips Potato Reg 43g', 89.33);
insert into Bakery_Menu (item_name, price) values ('Bread - Roll, Calabrese', 85.08);
insert into Bakery_Menu (item_name, price) values ('Compound - Strawberry', 46.74);
insert into Bakery_Menu (item_name, price) values ('Cornflakes', 27.51);
insert into Bakery_Menu (item_name, price) values ('Soup Campbells Split Pea And Ham', 62.83);
insert into Bakery_Menu (item_name, price) values ('Lettuce - Spring Mix', 88.65);
insert into Bakery_Menu (item_name, price) values ('Carbonated Water - Orange', 25.86);
insert into Bakery_Menu (item_name, price) values ('Oil - Canola', 55.72);
insert into Bakery_Menu (item_name, price) values ('Lamb - Pieces, Diced', 80.94);
insert into Bakery_Menu (item_name, price) values ('Cheese - St. Paulin', 49.37);
insert into Bakery_Menu (item_name, price) values ('Ham - Cooked Italian', 17.9);
insert into Bakery_Menu (item_name, price) values ('Garlic - Peeled', 10.64);
insert into Bakery_Menu (item_name, price) values ('Lemonade - Island Tea, 591 Ml', 51.03);
insert into Bakery_Menu (item_name, price) values ('The Pop Shoppe - Black Cherry', 17.34);
insert into Bakery_Menu (item_name, price) values ('Muffin - Banana Nut Individual', 74.08);
insert into Bakery_Menu (item_name, price) values ('Wine - Rubyport', 97.57);
insert into Bakery_Menu (item_name, price) values ('Wine - Fume Blanc Fetzer', 31.75);
insert into Bakery_Menu (item_name, price) values ('Coffee Caramel Biscotti', 80.38);
insert into Bakery_Menu (item_name, price) values ('Cake - Cheese Cake 9 Inch', 55.84);
insert into Bakery_Menu (item_name, price) values ('Cheese - Havarti, Salsa', 19.17);
insert into Bakery_Menu (item_name, price) values ('Yogurt - Blueberry, 175 Gr', 25.3);
insert into Bakery_Menu (item_name, price) values ('Cheese - Le Cheve Noir', 55.46);
insert into Bakery_Menu (item_name, price) values ('Potato - Sweet', 69.28);
insert into Bakery_Menu (item_name, price) values ('Tuna - Loin', 10.14);
insert into Bakery_Menu (item_name, price) values ('Phyllo Dough', 18.72);
insert into Bakery_Menu (item_name, price) values ('Squid - U - 10 Thailand', 64.46);
insert into Bakery_Menu (item_name, price) values ('Soup - Tomato Mush. Florentine', 82.06);
insert into Bakery_Menu (item_name, price) values ('Rice - Long Grain', 39.13);
insert into Bakery_Menu (item_name, price) values ('Foil - Round Foil', 56.95);
insert into Bakery_Menu (item_name, price) values ('Wine - Barossa Valley Estate', 50.49);
insert into Bakery_Menu (item_name, price) values ('Veal - Knuckle', 70.08);
insert into Bakery_Menu (item_name, price) values ('Ecolab - Ster Bac', 90.04);
insert into Bakery_Menu (item_name, price) values ('Shallots', 18.17);
insert into Bakery_Menu (item_name, price) values ('Island Oasis - Sweet And Sour Mix', 12.26);
insert into Bakery_Menu (item_name, price) values ('Soup - Cream Of Potato / Leek', 50.16);
insert into Bakery_Menu (item_name, price) values ('Buffalo - Striploin', 15.24);
insert into Bakery_Menu (item_name, price) values ('Table Cloth 62x120 Colour', 43.29);
insert into Bakery_Menu (item_name, price) values ('Wine - Merlot Vina Carmen', 45.06);
insert into Bakery_Menu (item_name, price) values ('Juice - V8 Splash', 84.19);
insert into Bakery_Menu (item_name, price) values ('Beer - Camerons Cream Ale', 39.5);
insert into Bakery_Menu (item_name, price) values ('Compound - Rum', 70.35);
insert into Bakery_Menu (item_name, price) values ('Ezy Change Mophandle', 62.81);
insert into Bakery_Menu (item_name, price) values ('Ecolab - Balanced Fusion', 67.31);
insert into Bakery_Menu (item_name, price) values ('Sauce - White, Mix', 56.54);
insert into Bakery_Menu (item_name, price) values ('Appetizer - Mango Chevre', 64.6);
insert into Bakery_Menu (item_name, price) values ('Wine - Red, Concha Y Toro', 97.88);
insert into Bakery_Menu (item_name, price) values ('Star Anise, Whole', 76.06);
insert into Bakery_Menu (item_name, price) values ('Bulgar', 71.46);
insert into Bakery_Menu (item_name, price) values ('Lembdas Bread', 99.99);